export const ROUTER_ERROR_DUPLICATED_SITE_SUBDOMAIN =
  'ROUTER_ERROR_DUPLICATED_SITE_SUBDOMAIN';
export const ROUTER_ERROR_DUPLICATED_PROJECT_DOMAIN =
  'ROUTER_ERROR_DUPLICATED_PROJECT_DOMAIN';
export const ROUTER_ERROR_3P_API_FAILED = 'ROUTER_ERROR_3P_API_FAILED';
export const ROUTER_ERROR_PRISMA_FAILED = 'ROUTER_ERROR_PRISMA_FAILED';
