export const ROUTER_ERROR_DUPLICATED_SITE_SUBDOMAIN =
  'ROUTER_ERROR_DUPLICATED_SITE_SUBDOMAIN';
export const ROUTER_ERROR_DUPLICATED_PROJECT_DOMAIN =
  'ROUTER_ERROR_DUPLICATED_PROJECT_DOMAIN';
export const ROUTER_ERROR_VERCEL_ADD_DOMAIN_FAILED =
  'ROUTER_ERROR_VERCEL_ADD_DOMAIN_FAILED';
export const ROUTER_ERROR_VERCEL_DELETE_DOMAIN_FAILED =
  'ROUTER_ERROR_VERCEL_DELETE_DOMAIN_FAILED';
