-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."NotificationSubscription" add column "createdAt" timestamptz
--  null default now();
