name: cypress
# https://glebbahmutov.com/blog/develop-preview-test/
on: [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1
      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
          HASURA_EVENT_SECRET: ${{ secrets.HASURA_EVENT_SECRET }}
          # DEBUG: 'cypress:*'
          # DEBUG_DEPTH: 9
