name: Publish Docker images

on:
  create:
    tags: ['v*']
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  build_push_chirpy:
    name: Chirpy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract meta
        id: builder-meta
        uses: docker/metadata-action@v4
        with:
          images: devrsi0n/chirpy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push builder image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.builder-meta.outputs.tags }}
          labels: ${{ steps.builder-meta.outputs.labels }}
          cache-from: type=registry,ref=devrsi0n/chirpy:buildcache
          cache-to: type=registry,ref=devrsi0n/chirpy:buildcache,mode=max
          # Don't put any sensitive key to build-args, as they'll be exposed to build history
          build-args: |
            NEXT_PUBLIC_HOME_ORIGIN=${{ secrets.NEXT_PUBLIC_HOME_ORIGIN }}
            NEXT_PUBLIC_ANALYTICS_DOMAIN=${{ secrets.NEXT_PUBLIC_ANALYTICS_DOMAIN }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
