name: Publish Docker images

on:
  create:
    tags: ['v*']
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  push_builder:
    name: Builder
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract meta
        id: builder-meta
        uses: docker/metadata-action@v4
        with:
          images: devrsi0n/chirpy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push builder image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.builder-meta.outputs.tags }}
          labels: ${{ steps.builder-meta.outputs.labels }}
          build-args:
            NEXT_PUBLIC_HASURA_HTTP_ORIGIN: ${NEXT_PUBLIC_HASURA_HTTP_ORIGIN}
            NEXT_PUBLIC_HASURA_WS_ORIGIN: ${NEXT_PUBLIC_HASURA_HTTP_ORIGIN}
            NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
            NEXT_PUBLIC_VAPID: ${NEXT_PUBLIC_VAPID}
            NEXT_PUBLIC_ANALYTICS_DOMAIN: ${NEXT_PUBLIC_ANALYTICS_DOMAIN}
            NEXTAUTH_URL: ${NEXTAUTH_URL}
            HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
            HASURA_EVENT_SECRET: ${HASURA_EVENT_SECRET}
            HASH_ALGORITHM: ${HASH_ALGORITHM}
            NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
            PRIVATE_VAPID: ${PRIVATE_VAPID}
            EMAIL_API_KEY: ${EMAIL_API_KEY}
            GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
            GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
            TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
            TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
